package com.udea.persistencia;
// Generated 3/10/2019 07:21:55 PM by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="ciudad"
    ,catalog="ciudadws"
)
public class Ciudad  implements java.io.Serializable {


     private Integer codigo;
     private String ciudad;
     private String departamento;
     private String tempActualCentigrados;
     private String tempActualFahrenheit;
     private String humedadActual;
     private String condensacionActual;
     private String presionActual;
     private String visibilidadActual;
     private String probabilidadPrecipitacion;
     private String descripcionProxtres;
     private String maxMinProxtres;
     private String precipitacionProxtres;
     private String vientoProxtres;
     private String humedadProxtres;

    public Ciudad() {
    }

    public Ciudad(String ciudad, String departamento, String tempActualCentigrados, String tempActualFahrenheit, String humedadActual, String condensacionActual, String presionActual, String visibilidadActual, String probabilidadPrecipitacion, String descripcionProxtres, String maxMinProxtres, String precipitacionProxtres, String vientoProxtres, String humedadProxtres) {
       this.ciudad = ciudad;
       this.departamento = departamento;
       this.tempActualCentigrados = tempActualCentigrados;
       this.tempActualFahrenheit = tempActualFahrenheit;
       this.humedadActual = humedadActual;
       this.condensacionActual = condensacionActual;
       this.presionActual = presionActual;
       this.visibilidadActual = visibilidadActual;
       this.probabilidadPrecipitacion = probabilidadPrecipitacion;
       this.descripcionProxtres = descripcionProxtres;
       this.maxMinProxtres = maxMinProxtres;
       this.precipitacionProxtres = precipitacionProxtres;
       this.vientoProxtres = vientoProxtres;
       this.humedadProxtres = humedadProxtres;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="ciudad", nullable=false)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="departamento", nullable=false)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="temp_actual_centigrados", nullable=false, length=5)
    public String getTempActualCentigrados() {
        return this.tempActualCentigrados;
    }
    
    public void setTempActualCentigrados(String tempActualCentigrados) {
        this.tempActualCentigrados = tempActualCentigrados;
    }

    
    @Column(name="temp_actual_fahrenheit", nullable=false, length=5)
    public String getTempActualFahrenheit() {
        return this.tempActualFahrenheit;
    }
    
    public void setTempActualFahrenheit(String tempActualFahrenheit) {
        this.tempActualFahrenheit = tempActualFahrenheit;
    }

    
    @Column(name="humedad_actual", nullable=false, length=20)
    public String getHumedadActual() {
        return this.humedadActual;
    }
    
    public void setHumedadActual(String humedadActual) {
        this.humedadActual = humedadActual;
    }

    
    @Column(name="condensacion_actual", nullable=false, length=20)
    public String getCondensacionActual() {
        return this.condensacionActual;
    }
    
    public void setCondensacionActual(String condensacionActual) {
        this.condensacionActual = condensacionActual;
    }

    
    @Column(name="presion_actual", nullable=false, length=20)
    public String getPresionActual() {
        return this.presionActual;
    }
    
    public void setPresionActual(String presionActual) {
        this.presionActual = presionActual;
    }

    
    @Column(name="visibilidad_actual", nullable=false, length=20)
    public String getVisibilidadActual() {
        return this.visibilidadActual;
    }
    
    public void setVisibilidadActual(String visibilidadActual) {
        this.visibilidadActual = visibilidadActual;
    }

    
    @Column(name="probabilidad_precipitacion", nullable=false)
    public String getProbabilidadPrecipitacion() {
        return this.probabilidadPrecipitacion;
    }
    
    public void setProbabilidadPrecipitacion(String probabilidadPrecipitacion) {
        this.probabilidadPrecipitacion = probabilidadPrecipitacion;
    }

    
    @Column(name="Descripcion_proxtres", nullable=false)
    public String getDescripcionProxtres() {
        return this.descripcionProxtres;
    }
    
    public void setDescripcionProxtres(String descripcionProxtres) {
        this.descripcionProxtres = descripcionProxtres;
    }

    
    @Column(name="max_min_proxtres", nullable=false, length=20)
    public String getMaxMinProxtres() {
        return this.maxMinProxtres;
    }
    
    public void setMaxMinProxtres(String maxMinProxtres) {
        this.maxMinProxtres = maxMinProxtres;
    }

    
    @Column(name="precipitacion_proxtres", nullable=false, length=20)
    public String getPrecipitacionProxtres() {
        return this.precipitacionProxtres;
    }
    
    public void setPrecipitacionProxtres(String precipitacionProxtres) {
        this.precipitacionProxtres = precipitacionProxtres;
    }

    
    @Column(name="viento_proxtres", nullable=false, length=20)
    public String getVientoProxtres() {
        return this.vientoProxtres;
    }
    
    public void setVientoProxtres(String vientoProxtres) {
        this.vientoProxtres = vientoProxtres;
    }

    
    @Column(name="humedad_proxtres", nullable=false, length=20)
    public String getHumedadProxtres() {
        return this.humedadProxtres;
    }
    
    public void setHumedadProxtres(String humedadProxtres) {
        this.humedadProxtres = humedadProxtres;
    }

    @Override
    public String toString() {
        return "Ciudad{" + "codigo=" + codigo + ", ciudad=" + ciudad + ", departamento=" + departamento + ", tempActualCentigrados=" + tempActualCentigrados + ", tempActualFahrenheit=" + tempActualFahrenheit + ", humedadActual=" + humedadActual + ", condensacionActual=" + condensacionActual + ", presionActual=" + presionActual + ", visibilidadActual=" + visibilidadActual + ", probabilidadPrecipitacion=" + probabilidadPrecipitacion + ", descripcionProxtres=" + descripcionProxtres + ", maxMinProxtres=" + maxMinProxtres + ", precipitacionProxtres=" + precipitacionProxtres + ", vientoProxtres=" + vientoProxtres + ", humedadProxtres=" + humedadProxtres + '}';
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.codigo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ciudad other = (Ciudad) obj;
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        return true;
    }




}


